spring.application.name=sync-study-backend
spring.datasource.url=jdbc:mysql://localhost:3306/sync_study?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=565627